typography_spectrum: 0.30566
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5085928298067302
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.65856
analytics:
  google: null
  facebook: null
  twitter: null
name: webapp
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Add a “buy now” button
    id: e80fb260-6b8a-47d0-bb41-5ef7aef40ae2
    type: content
favicon: null
title: The Grid's web app
purpose: []
